source 'https://rubygems.org'

ruby '~> 3.1'

gem 'activerecord', '~> 7.1.0'
gem 'sqlite3',      '~> 1.7'
gem 'graphql',      '~> 2.6', '>= 2.6.3'
gem 'karafka',      '~> 2.0', '>= 2.0.21'

# IRuby kernel for Jupyter notebooks
gem 'iruby'
gem 'cztop'
