apiVersion: v1
kind: Pod
metadata:
  labels:
    run: dry_run_test_pod
  name: dry_run_test_pod
spec:
  containers:
  - image: httpd
    name: dry_run_test_pod
    resources: {}
  dnsPolicy: ClusterFirst
  restartPolicy: Always
status: {}
